export default {
  UNVERIFIED: 'UNVERIFIED',
  NO_NHS_LINKAGE: 'NO_NHS_LINKAGE',
  INITIAL: 'INITIAL',
  FIRST_DOSE_CONFIRMED: 'FIRST_DOSE_CONFIRMED',
  SECOND_DOSE: 'SECOND_DOSE',
  AWAITING_VACCINATION: 'AWAITING_VACCINATION',
  VACCINATION_CONFIRMED: 'VACCINATION_CONFIRMED',
  IMMUNITY_CONFIRMED: 'IMMUNITY_CONFIRMED'
};
