/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:d99db4d4-b148-4ba9-b227-82fa5c839428",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_YSsI8CiIR",
    "aws_user_pools_web_client_id": "586s5ui98l82rq1b6a3uovi8qf",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://yc53c2cn65gejajnlp3qcb4lgq.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-pz4lrvuw5nfwjdffwoaus52avu",
    "aws_user_files_s3_bucket": "checkmenow162307-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_mobile_analytics_app_id": "ced2590e1b084482ac71454d4391d730",
    "aws_mobile_analytics_app_region": "eu-west-1"
};


export default awsmobile;
